apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-mongo-depl
  labels:
    app: tickets-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-mongo
  template:
    metadata:
      labels:
        app: tickets-mongo
    spec:
      containers:
        - name: tickets-mongo
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-mongo-srv
  labels:
    app: tickets-mongo
spec:
  selector:
    app: tickets-mongo
  ports:
    - name: db
      protocol: TCP
      #default port for mongo - do research in docker hub image
      port: 27017
      targetPort: 27017
